#pragma once

#include "commons/math/general.hh"
#include "commons/math/interpolation.hh"
#include "commons/math/linesegment.hh"
#include "commons/math/circle.hh"
#include "commons/math/sphere.hh"
#include "commons/math/aabb.hh"
#include "commons/math/capsule.hh"
#include "commons/math/triangle.hh"
#include "commons/math/quad.hh"
#include "commons/math/util.hh"
#include "commons/math/quaternion.hh"
#include "commons/math/vec2.hh"
#include "commons/math/vec3.hh"
#include "commons/math/vec4.hh"
#include "commons/math/mat3.hh"
#include "commons/math/mat4.hh"
